theme = "dracula_at_night"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
idle-timeout = 200
line-number = "relative"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "file-name", "version-control", "spacer", "spinner"]
right = ["diagnostics", "file-type", "file-encoding", "file-line-ending", "selections", "spacer", "position-percentage", "position"]
