theme = "dracula"

[editor]
color-modes = true
cursorline = true
idle-timeout = 200
line-number = "relative"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true
